# source 'https://github.com/CocoaPods/Specs.git'
# source 'http://192.168.40.117:10080/iOS/Specs.git'
# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

use_frameworks!

workspace 'analyse'

def snapkit
    pod 'SnapKit', '3.2.0'
end

def alamofire
    pod 'Alamofire', '4.4.0'
end

def libPhoneNumber
    pod 'libPhoneNumber-iOS', '~> 0.9.6'
end

def moya
    pod 'Moya/RxSwift', '8.0.3'
end

def rxswift
    pod 'RxSwift', '3.4.0'
    pod 'RxCocoa', '3.4.0'
end

def swiftyjson
    pod 'SwiftyJSON', '3.1.4'
end

def objectmapper
    pod 'ObjectMapper', '2.2.5'
end

def mjrefresh
    pod 'MJRefresh', '3.1.12'
end

def mbprogressHUD
    pod 'MBProgressHUD', '1.0.0'
end

def reachabilityswift
    pod 'ReachabilitySwift', '3'
end

def mgswipetablecell
    pod 'MGSwipeTableCell', '1.5.6'
end

def swiftdate
    pod 'SwiftDate', '4.1.1'
end

def mleaksfinder
    pod 'MLeaksFinder', :configurations => ['Debug']
end

def sdwebimage
    pod 'SDWebImage', '4.0.0'
end

def fscalendar
    pod 'FSCalendar', '2.7.4'
end

def monkeyking
    pod 'MonkeyKing', '1.2.3'
end

def yytext
    pod 'YYText', '1.0.7'
end

def icarousel
    pod 'iCarousel', '1.8.3'
end

def fdfullscreenpopgesture
    pod 'FDFullscreenPopGesture', '1.1'
end

def keychainAccess
    pod 'KeychainAccess', '3.0.2'
end

def mleaksfinder
    pod 'MLeaksFinder', :configurations => ['Debug']
end

def dkimagepicker
    pod 'DKImagePickerController', '3.5.1'
end

def spreadsheetview
    pod 'SpreadsheetView', '0.8.0'
end

def sideMenu
    pod 'SideMenu'
end

def app
    snapkit
    alamofire
    
    rxswift
    reachabilityswift
    
    mjrefresh
    mgswipetablecell
    mbprogressHUD
    
    sdwebimage
    monkeyking
    
    swiftdate
    fscalendar
    yytext
    fdfullscreenpopgesture
    icarousel
    swiftyjson
    moya
    objectmapper
    
    keychainAccess
    libPhoneNumber
    
    mleaksfinder
    dkimagepicker
    spreadsheetview
    
    sideMenu

end

target 'zhuzhu' do
    project 'zhuzhu/zhuzhu.xcodeproj'
    
    app
end

target 'Common' do
    project 'Common/Common.xcodeproj'
    
    mbprogressHUD
    alamofire
    reachabilityswift
    swiftdate
    snapkit
    rxswift
    yytext
    fdfullscreenpopgesture
    libPhoneNumber
    icarousel
    swiftyjson
    mjrefresh
    objectmapper
    
    keychainAccess
end

target 'FMNetwork' do
    project 'FMNetwork/FMNetwork.xcodeproj'
    
    moya
    snapkit
    rxswift
    yytext
    swiftyjson
    mjrefresh
    objectmapper
    mbprogressHUD
    libPhoneNumber
    icarousel
    reachabilityswift
    
end

inhibit_all_warnings!

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.2'
        end
    end
end

